  services:
    frontend:
      build: .
      ports:
        - "5173:5173"
      env_file:
        - .env
      depends_on:
        - digirunner

    digirunner:
      image: tpisoftwareopensource/digirunner-open-source
      ports:
        - "31080:18080"
      environment:
        - TZ=Asia/Taipei
        - SPRING_DATASOURCE_URL=jdbc:h2:file:/opt/digirunner/data/dgrdb;DB_CLOSE_DELAY=-1;NON_KEYWORDS=VALUE;Mode=MySQL
        - SPRING_SQL_INIT_CONTINUE_ON_ERROR=true
        - JAVA_OPTS=-Xms512m -Xmx2g -XX:TieredStopAtLevel=1 -XX:+UseG1GC
        - SPRING_MAIN_LAZY_INITIALIZATION=true
      volumes:
        - digirunner_data:/opt/digirunner/data
        - digirunner_keys:/opt/digirunner/keys
      restart: unless-stopped


  volumes:
    digirunner_data:
    digirunner_keys: